version: '3'

services:
  starlette:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: predict_food_local_starlette
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: uvicorn server:app --reload --host 0.0.0.0 --port 5000